### ISSUE TITLE
doesn't work with static IP address 

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-net-macosx#3]
Seems that only DHCP works.

**Comment by yomimono** [comment]
@samoht do you have any sense for how hard this will be to fix? I have no equipment for looking into it these days but it might be a nice first bug for someone, unless you think it's thorny.

**Comment by MagnusS** [comment]
I don’t think Vmnet.framework supports it. According to the documentation it seems to be ipv4 over dhcp only: https://developer.apple.com/documentation/vmnet

**Comment by yomimono** [comment]
OK.  In that case we should find a way to expose that this won't work at configure time in `mirage`.

**Comment by yomimono** [comment]
This is now noted in the README and there's an issue in mirage/mirage for it, so I'll close this.
