### ISSUE TITLE
pls release

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-net-macosx#8]
according to @thornleyk in https://github.com/ocaml/opam-repository/pull/5808#issuecomment-259847477 this package needs a release (and previous releases need adjustments) -- I see that @samoht did remove the camlp4 earlier (thus master should work with an up to date sexplib)

**Comment by samoht** [comment]
Let me have a look at this.

**Comment by hannesm** [comment]
@samoht thx! (I don't have a computer to test this package on...)   I can also see there is some _oasis in this repo..

**Comment by hannesm** [comment]
done in https://github.com/ocaml/opam-repository/pull/7807, thx to @samoht
